### ISSUE TITLE
Mac Build?

### ISSUE THREAD

**Issue by flewid** [microp11/iridiumlive#17]
Is it possible to get a mac build or, can I help you get it built?

**Comment by microp11** [comment]
I would appreciate it if you want to build it for Mac.
I will not be able to test it as I do not own one, and I won't publish binaries I did not build myself. As a programmer you would understand why.

But I would encourage you to clone the repo, modify/build/create PR if you want and upload the Mac binary under your own clone.

Also, there are so many things that can be done which were left on the back-burner due to time constraints. If interested to work on adding new features, please let me know.

**Comment by flewid** [comment]
Great thanks. I was actually able to build this without too much issue - it does show a warning, but doesn't seem to matter because everything works. 

Question - when I'm running this - can I also run another command to output the decoded packets to a file for furthur analysis? I wasn't sure if I can run gr-iridium 'twice' at the same time?

**Comment by microp11** [comment]
Excellent.

The packets are redirected through pipes. 
The easiest I imagine, would be to capture all the packets (already done) into the database and then analyze them using queries. If data gets trimmed down, which you need to check as I do not recall, you'll just ensure it does not. Or you could save all to files and read the files back into the app at the same time. Then you have both worlds, the toolkit and the database.

**Comment by flewid** [comment]
okay great thank you will play with it :)

**Comment by microp11** [comment]
Did it work?

**Comment by flewid** [comment]
I was unable to get it working at the time - But I plan on re-investigating this in the near future. If you'd like to close this I can re-open it once I do.

**Comment by microp11** [comment]
Will do, thanks for letting me know.
