### ISSUE TITLE
live page no data

### ISSUE THREAD

**Issue by czl1989** [microp11/iridiumlive#2]
fail : microsoft. entity framework core. database. command[20102]

**Comment by microp11** [comment]
It seems that the db cannot be created for some reason. After you run the app, Is there a file named: IridiumLive.db in the same folder as the app? Which os? Permissions perhaps? Your own build or the prerelease build I made?

**Comment by microp11** [comment]
Do other pages show any data? Satellites, Statistics...?

**Comment by czl1989** [comment]
I use prerelease beacause the source code has no map ubuntu18.04.Ather pages show well. Run app ，the db file locked，use chmod 777 unlock.

**Comment by czl1989** [comment]
> Do other pages show any data? Satellites, Statistics...?

I use prerelease beacause the source code has no map ubuntu18.04.Ather pages show well. Run app ，the db file locked，use chmod 777 unlock.

**Comment by czl1989** [comment]
> Do other pages show any data? Satellites, Statistics...?

I use prerelease because the source code has no map ubuntu18.04.Other pages show well. Run app ，the db file locked，use chmod 777 unlock.

**Comment by czl1989** [comment]
![15765736884920 43206725258604295](https://user-images.githubusercontent.com/38196034/70981277-7b99d700-207a-11ea-9e7d-6fe86bfc3128.jpg)
live page no data

**Comment by TechMindsYT** [comment]
I have the same issue, apart from with mine ONLY the SATS tab has data. I have attached my IridiumLive.db

By the way, I am TechMindsYT from twitter/youtube :-)

[IridiumLive.zip](https://github.com/microp11/iridiumlive/files/3973770/IridiumLive.zip)

**Comment by czl1989** [comment]
I had a output. bits. I use iridium-parser. py parse it，the number of IRA is 199.But statistics page Ring alerts total number is 107.What happened?

**Comment by microp11** [comment]
> I had a output. bits. I use iridium-parser. py parse it，the number of IRA is 199.But statistics page Ring alerts total number is 107.What happened?

I could think of several things. remains to be discovered.

1. We do keep track of the messages received, that means currently we cannot count them. One solution is to tag them at the transmission in the python script and then count them on the app side. This is easy and I will write the code, just to be able to get some time. This way we would know which messages get lost.
2. The protocol used to link the iridium-parser to the app is UDP. There are two reasons. 
- One, the UDP is broadcast based, which means there is no need for the receiver (app) to be on while the transmitter transmits.
- Two, if the receiver is to slow to listen, the transmitter does not care and still works at full speed.
So if the network is good, we could implement a buffer on the receiver side that gets filled at full network speed and then we can process fully as breaks in transmission occur.

**Comment by microp11** [comment]
> I have the same issue, apart from with mine ONLY the SATS tab has data. I have attached my IridiumLive.db
> 
> By the way, I am TechMindsYT from twitter/youtube :-)
> 
> [IridiumLive.zip](https://github.com/microp11/iridiumlive/files/3973770/IridiumLive.zip)

Never-mind the below. No need to change anything but some frequency range for the gr-iridium capturing. The reason for not seeing IRAs is that they are only sent on specific frequencies, so you will need to adjust your receiver to get the pager signals. IBCs are sent all over so you will have those received.

Hi! This is much appreciated. 
Again, wish I would have implemented a buffer to hold all the data received. Will have to.
I have received the log file and I cannot find any IRAs in it, just IBCs. So perhaps somehow they get filtered out at the source. The Live view only displays IRAs.
I see IBCs and no IRAs and IRAs are used for the live display.
Please modify the grep filter inside the pipe to catch IRAs, something like:
instead of ... | grep "sat:" | ...
have:
| grep "IRA:" | 
or just remove the grep altogether.

Initially I thought the parser is faulty, it looks like there is something else. If still nothing, please send me a bit of the log that contains both IBCs and IRAs. Thanks.

**Comment by microp11** [comment]
The IRAs are only sent on specific frequencies. Please modify your center frequency in the configuration file for the gr-iridium to include the pager signals.

**Comment by czl1989** [comment]
> The IRAs are only sent on specific frequencies. Please modify your center frequency in the configuration file for the gr-iridium to include the pager signals.

I try the grep "IRA" command. The statistic page ring alert number is right. But the live page  also no date. Last page update also no time.

**Comment by microp11** [comment]
> > The IRAs are only sent on specific frequencies. Please modify your center frequency in the configuration file for the gr-iridium to include the pager signals.
> 
> I try the grep "IRA" command. The statistic page ring alert number is right. But the live page also no date. Last page update also no time. I have attached my db file and screenshot.
> [Screenshot.zip](https://github.com/microp11/iridiumlive/files/3977310/Screenshot.zip)
> [IridiumLive.zip](https://github.com/microp11/iridiumlive/files/3977287/IridiumLive.zip)

I do not know why it behaves like this. The Live is "live" and the capability to see "playback" or view older records is not implemented yet. I would say open in two tabs or browser, leave on on the statistics and one on the live. If you see records updating on statistics and nothing on live, please send me a copy of your database or a portion of a log that contains IRAs. Thanks.

**Comment by czl1989** [comment]
> > > The IRAs are only sent on specific frequencies. Please modify your center frequency in the configuration file for the gr-iridium to include the pager signals.
> > 
> > 
> > I try the grep "IRA" command. The statistic page ring alert number is right. But the live page also no date. Last page update also no time. I have attached my db file and screenshot.
> > [Screenshot.zip](https://github.com/microp11/iridiumlive/files/3977310/Screenshot.zip)
> > [IridiumLive.zip](https://github.com/microp11/iridiumlive/files/3977287/IridiumLive.zip)
> 
> I do not know why it behaves like this. The Live is "live" and the capability to see "playback" or view older records is not implemented yet. I would say open in two tabs or browser, leave on on the statistics and one on the live. If you see records updating on statistics and nothing on live, please send me a copy of your database or a portion of a log that contains IRAs. Thanks.

I tried to leave one on the statistics and one on the live. the statistics updated but live page no data The live page receive IRA from UDP. I use iridium-parser.py to parse previous data and send it now.  Can it know whether it is receiving real-time data or previous data.

**Comment by microp11** [comment]
This is excellent information and I have found the reason your screen won't display anything:

![Capture](https://user-images.githubusercontent.com/1545798/71141895-ffbf9c00-21eb-11ea-8ffb-bd48acd4f031.JPG)

It seems that the software interprets the time the wrong way. we know that the Iridium time is different than Linux but in all my test it was just a few seconds. In your case it is a year. 

So everything works as it should, except the map won't display anything because the software will only look back about 10 seconds for the first time the "live" is opened.

I will have to investigate this.

The parser is working fine:
![data](https://user-images.githubusercontent.com/1545798/71142130-d6ebd680-21ec-11ea-9663-1643dca58c34.JPG)
as seen here by looking at the database you provided.

The time I see in the database you provided starts like this:

IRA: i-**1516353084**-t1 000001659 1626286208  99%   0.007 093 DL **sat:48** beam:41 pos=(+31.61/+104.91) alt=017 RAI:48 ?10 bc_sb:21 PAGE(NONE) descr_extra:01101011010111100111001111

while the time that I receive with my computer looks like this for the same satellite:
IRA: i-**1576457556**-t1 181328752 1626225536 100%   0.031 093 DL **sat:48** beam:38 pos=(+39.51/-058.21) alt=013 RAI:48 ?10 bc_sb:24 PAGE(NONE)

And this time translates to:
![data2](https://user-images.githubusercontent.com/1545798/71142719-9d1bcf80-21ee-11ea-9c4b-7dc6f4aa3e81.JPG)

So I am thinking there has to be something different on your system, I have no idea what, which will make the time you receive so different. Do you have latest gr-iridium? The time is set correctly, what if you change the time zone to UTC for some tests?

**Comment by microp11** [comment]
Another factor that would indicate something odd with your settings is that the time reported from the east cost and west coast of north america as well as time reported from europe is within a few seconds behind GMT. i do not know.

**Comment by czl1989** [comment]
Thanks.

**Comment by microp11** [comment]
> Thanks.

I see you closed the case. Is your problem fixed? what was it? your system time?

**Comment by czl1989** [comment]
> > Thanks.
> 
> I see you closed the case. Is your problem fixed? what was it? your system time?

Yes. The system time was not right. System time must be the same as IRA time. Thanks.
